### ISSUE TITLE
[cetic/job] command + args don't work

### ISSUE THREAD

**Issue by DrPsychick** [cetic/helm-job#1]
**Describe the bug**
Using the `command` or `args` examples from the `values.yaml` does not work.

**Version of Helm and Kubernetes**:
```helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}```
```

**What happened**:
The generated template is missing quotes
```
    env:
        - name: "ENV_VAR_TEST"
          value: "Test content"
        command: [/bin/sh]
        args: [-c echo 'consuming a message'; ps faxuwww; echo 'ENV_VAR_TEST='$(ENV_VAR_TEST)' != '$ENV_VAR_TEST; sleep 5]
```

**What you expected to happen**:
Add command and args as lists with quotes
```
env:
        - name: "ENV_VAR_TEST"
          value: "Test content"
        command: 
          - "/bin/sh"
        args: 
          - "-c"
          - "echo 'consuming a message'; ps faxuwww; echo 'ENV_VAR_TEST='$(ENV_VAR_TEST)' != '$ENV_VAR_TEST; sleep 5"
```

**How to reproduce it** (as minimally and precisely as possible):
```
command: ["/bin/sh"]
args: ["-c", "echo 'works'; sleep 5"]
```
